apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop  # <-- don't forget
  labels: 
    component: shipping
    project: roboshop
    tier: app
data: 
   CART_ENDPOINT: "cart:8080"    # Remove equal symbol(=), and coloun symbol(:)
   DB_HOST: "mysql"
---
# 🔎 kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shipping
  namespace: roboshop  # edi evvakapote default namespace lo run avutumdhi.
# deployment labels
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels: 
      component: shipping
      project: roboshop
      tier: app
# This is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers: 
      - name: shipping
        image: kalyantalabothula/shipping:v1  # Mii Docker hub nimdi pull chesukuntumdhi, username,Password Evvakunda ante? --> Public image kabatti it will pull.  
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"  # Because java realated Application kabatti manam, dhiniki kumchum yekkuva evvali.
          limits:
            cpu: "200m"
            memory: "512Mi"
        envFrom: 
        - configMapRef:  # <-- Environments ni configMap resourceses lo catalogue anedi undi akkada nimdi refer chesuko, akkada unne env catalogue dhi. 
            name: shipping   
# manam separate gha kuda configMap manifest.yaml file ni pettukovachhu, but manam GitBash lo everytime manam $ kubectl apply -f configmap.yaml ani evvali. ala evvakunda manam ela chesunnam. mottam okka manifest.yaml lo petti apply chestunnam. Like config.yaml ani, Deployment.yaml ani, service.yaml ani, 3 times avvali apply ani. Andhuke manam order lo petti estunnam. 
---
apiVersion: v1
kind: Service
metadata: 
  name: shipping
  namespace: roboshop   # <--
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container Port 
---
# yela ina cheyachhu like command-line dwara ina or yaml ina. manam yaml dwara cheydham.
# 🔎 horizontal autoscaling kubernetes --> HorizontalPodAutoscaler Walkthrough
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: shipping   # <---
  namespace: roboshop   # <-- don't forget namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping # < -- which Deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10    # <--
# eppudu e HPA resources continous gha Deployment ni watch chestumdhi, ee Deployment lo yenni Pods unnayo dhani yokka averageCPUUtilization 10% kante yekkuva unte, Then it will create the Pod replicas Until 10.