apiVersion: v1
kind: Service
metadata: 
  name: mongodb-headless
  namespace: roboshop   # <--- namespace
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None   # <-- capital letter --> N 
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container Port 
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-headless
  namespace: roboshop   # <--- namespace
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container Port 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop   # <--- namespace
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  serviceName: "mongodb-headless"    # <-- This should be Headless Service
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: kalyantalabothula/mongodb:v1
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
# This is nothing but PVC, you can directly create here volumeClaimTemplate ani OR create separatly. 
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"  # <-- create cheysina StorageClass name ekkada evvali. 
      resources:
        requests:
          storage: 2Gi

# 1st Storageclass(SC) create cheyali --> namespace --> Normal Service undali --> Headless Service undali --> PVC undali. edi anta cheste mii application kubernetes lo Stateful gha RUN avutaii.
