# 🔎 kubernetes pod screte
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque    #--> manam define chestunnam kabatti andhuke Opaque
data: 
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="   # <---
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-headless
  namespace: roboshop   # <--- namespace
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None   # <-- capital letter --> N 
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container Port 
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-headless
  namespace: roboshop   # <--- namespace
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container Port 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop   # <--- namespace
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  serviceName: "mysql-headless"    # <-- This should be Headless Service
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: kalyantalabothula/mysql:v1
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
# This is nothing but PVC, you can directly create here volumeClaimTemplate ani OR create separatly. 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"  # <-- create cheysina StorageClass name ekkada evvali. 
      resources:
        requests:
          storage: 2Gi

# 1st Storageclass(SC) create cheyali --> namespace --> Normal Service undali --> Headless Service undali --> PVC undali. edi anta cheste mii application kubernetes lo Stateful gha RUN avutaii.
