apiVersion: v1
kind: Service
metadata: 
  name: redis-headless
  namespace: roboshop   # <--- namespace
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None   # <--- Headless service
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container Port 
---
apiVersion: v1
kind: Service
metadata: 
  name: redis
  namespace: roboshop   # <--- namespace
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container Port 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop   # <--- namespace
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  serviceName: "redis-headless"    # <-- This should be Headless Service
  replicas: 2   # by default is 1
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis:7.0
        volumeMounts:
        - name: redis-data
          mountPath: /data
# This is nothing but PVC, you can directly create here volumeClaimTemplate ani OR create separatly. 
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"  # <-- create cheysina StorageClass name ekkada evvali. 
      resources:
        requests:
          storage: 2Gi

# 1st Storageclass(SC) create cheyali--> Normal Service undali --> Headless Service undali --> PVC undali. edi anta cheste mii application kubernetes lo Stateful gha RUN avutaii.